language: node_js
node_js:
  - 12.20.1
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: 12.20.1
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      dist: xenial
      services: docker
      language: generic
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.cache/electron'
    - '$HOME/.cache/electron-builder'
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn electron:build --linux deb --win nsis"
    else
      yarn electron:build
    fi
before_cache:
  - sudo chown -R travis:travis $HOME/.cache
  - sudo chown -R travis:travis $TRAVIS_BUILD_DIR/
  - rm -rf $HOME/.cache/electron-builder/wine
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nX+u6n29uHAT8wtOvUtGLCwtHiO85HsmJwEvfgIcLm9WOADxEDml/gaDxZDQ4ch8OPCUWbNNBRaksOizM7ZdwxYmunf4ulWqg8Vj09NaXqH+asl6WNRVP07YS9DZIKWczfbassSYZIV5VduNcVJ3n1J1hbD57mOAVXA0YBWZBX8FSyDB42xYvJoaYxsx9UKftKwLAqV9/vpFxhrflMnVlskgKfAx1ybkbYVfh6tFKUGRvD9MJTP39j+rC7wp1ojQisDEZeUS6ZRBwJUci1RVxddW9oPiKgQRtOfKgkIbZ9kNIoVSPhx0qAyYzuc1cxev77Vdwh9D2nePwzB6fhgSW4GXV5atJiZaFdheNvSyTxgA9Ck9IdDwjOLyXmitcmi+jOe2+dPrGowtWdJR6SXvIeIWj8nNTfD43BbWKxRBrIrUPjminOTwP78+MBETq6JSdJt7fPgbn54mJmpMIHdTiD/sJ1Dx86b6OZS83r5fGaj3Av17BwX3AMDCZyR2b9sYnIKYryow9YZftUUyMpmz2A0UlKvwWGGMMAqi2nPgCEo0GB5njmXZN/Xuj9V5QAo/e8zOC/u8EJxQq+oWBPASXXsxGjbDt73fhfK06lzUbUk4oecFGH4peB5/lfNUVNtHoJA185LlEtkIWlVqdZtZg43YBkMhH9ZydSfMexiUiec=
  file_glob: true
  file:
    - dist_electron/moosync*.AppImage
    - dist_electron/moosync*.deb
    - dist_electron/moosync*.dmg
    - dist_electron/moosync*.exe
  on:
    tags: true
